### ISSUE TITLE
出力ドライバー: Shapefile（シェープファイル）

### ISSUE THREAD

**Issue by sorami** [MIERUNE/PLATEAU-GIS-Converter#198]
調査メモ: [RustでShapefile](https://www.notion.so/mierune/Rust-Shapefile-d4012e6700ad41cbb3d5ab26e669a552)

## TODO

- [x] クレート作成 #203
- [x] MultiPointの変換 #203 
- [x] MultiLineStringの変換 #209 
- [x] MultiPolygonの変換 #209 
- [x] Shapefile Sink #214 
  - （#222 の例を参考にする）
- [x] App（Tauri）でのSink利用 #239 

***

- 属性付与
  - [x] #202 
  - [x] #423
  - [x] #424
  - 次期リリースで対応
    - #425
- [x] ファイル分割
- [x] #426
- [x] #427

***

- 座標系設定
  - [x] #333 
  - [x] #428
  - [x] #457
  - 各CRSのWKTは、gpkgでも使っているのでそちらを利用できる
    -  https://github.com/MIERUNE/PLATEAU-GIS-Converter/blob/main/nusamai-gpkg/src/sql/srs.sql

***

- 対応しない予定
  - #429

***

-  MulitiPoint, MultiLineStringへの対応

**Comment by nokonoko1203** [comment]
リリース目標は達成
