### ISSUE TITLE
GUI：gmlファイルがないフォルダを処理しても「出力されました」メッセージが表示される

### ISSUE THREAD

**Issue by xinmiaooo** [MIERUNE/PLATEAU-GIS-Converter#411]
![スクリーンショット 2024-03-07 13 52 45](https://github.com/MIERUNE/PLATEAU-GIS-Converter/assets/83005951/4e4b0516-c552-4b6c-b7f3-db6bf2951089)

**Comment by xinmiaooo** [comment]
例：
存在してないフォルダに出力と指定しても、処理が正常終了して、出力ファイルがない。
<img width="1197" alt="スクリーンショット 2024-03-07 15 22 19" src="https://github.com/MIERUNE/PLATEAU-GIS-Converter/assets/83005951/5cea47a9-7de2-423c-adbd-a3f5afadfb50">

**Comment by sorami** [comment]
@xinmiaooo 

> 存在してないフォルダに出力と指定

よくわかっていないのですが、これは、issueタイトルにある「gmlファイルがないフォルダ」を選択する話とは、また別の件でしょうか。

「存在してない（出力）フォルダ」は、GUI上から選択可能なのでしょうか？

**Comment by sorami** [comment]
#419, #430 で対応。
