### ISSUE TITLE
Github Actionsでビルドしたものは、Windows, shp(urfのみ)の変換中でクラッシュする。

### ISSUE THREAD

**Issue by xinmiaooo** [MIERUNE/PLATEAU-GIS-Converter#459]
https://www.notion.so/mierune/Tauri-Windows-8339fbe66d5d44f98d204f8e34108df2
の手順でBuildして実行したらクラッシュしない

**Comment by ciscorn** [comment]
現在は解決している模様。tokyo, numazu, tsukuba (2022) の全ての url を読ませて検証した。
