### ISSUE TITLE
glTF 2.0 のモデルをレビューする

### ISSUE THREAD

**Issue by ciscorn** [MIERUNE/PLATEAU-GIS-Converter#51]
glTFモデルは、公式の JSON Schema (https://github.com/KhronosGroup/glTF/tree/main/specification/2.0/schema) をもとに機械的に雑に生成したものが多いので、内容を目視でひとしきりチェックしておきたい。

https://github.com/MIERUNE/nusamai/tree/main/nusamai-gltf/src/models

- デフォルト値の扱い。
- 型付け
- etc.

**Comment by nokonoko1203** [comment]
3D Tilesが問題なく出力できているので、クローズ
問題が発生したら再度オープン
