### ISSUE TITLE
atlas: アトラス化の実行速度を計測できるようにexamplesを改良する

### ISSUE THREAD

**Issue by nokonoko1203** [MIERUNE/plateau-gis-converter#601]

**Comment by yud0uhu** [comment]
ベンチマークの計測
- [cargo-bench](https://doc.rust-lang.org/cargo/commands/cargo-bench.html)
- [criterion.rs](https://github.com/bheisler/criterion.rs)

**Comment by nokonoko1203** [comment]
一旦クローズ
