### ISSUE TITLE
gltf:全フォルダを変換にかけると、地物が傾く

### ISSUE THREAD

**Issue by satoshi7190** [MIERUNE/plateau-gis-converter#609]
竹芝の全データを一気に変換すると発生する
以下のファイルを巻き込むと傾く
`13999_tokyo_mlit_2023_citygml_1_op/udx/unf/09LD283_unf_10170_op.gml`
```sh
cargo run -- "13999_tokyo_mlit_2023_citygml_1_op/udx/**/*.gml" --sink gltf --output <out_path>   
```
![image](https://github.com/user-attachments/assets/d4e2d5a7-e44d-4638-be45-2b66b73b04ff)

**Comment by nokonoko1203** [comment]
地下埋設物が含まれると座標が正確に読み取れないという別の問題のため、クローズ
